# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

def generate_new_pents(pents, pent_values, i, j)
  k = pents.length - 1
  until pents.last >= pents[i] + pents[j]
    k += 1
    pents << k * (3 * k - 1) / 2
    pent_values[k * (3 * k - 1) / 2] = true
  end
end

pents = [1, 5]
pent_values = { 1 => true, 5 => true }
j = 1

while true
  p j
  i = j - 1
  unless pents.last >= pents[i] + pents[j]
    generate_new_pents(pents, pent_values, i, j)
  end
  while i >= 0
    if pent_values[pents[j] + pents[i]] &&
      pent_values[pents[j] - pents[i]]
      answer = pents[j] - pents[i]
      break
    end
    i -= 1
  end
  break if !!answer
  j += 1
end

p answer
